name: Build and deploy DEB package
description: Builds DEB package and deploys it to GitHub Pages as APT repository
inputs:
  package-name:
    description: Name of the package
    required: true
  package-root:
    description: Path to directory containing the package content
    required: true
  maintainer:
    description: Maintainer of the package
    required: true
  version:
    description: Version of the package
    required: true
  arch:
    description: Supported arch of this package
    default: 'all'
  depends:
    description: List of package dependencies
    default: 'none'
  description:
    description: Description of the package
    required: true
  homepage:
    description: URL of homepage belonging to package
    required: true
  token:
    description: Token used to authenticate against GitHub API
    required: true
  gpg-private-key:
    description: Private key used to sign repository
    required: false
  gpg-public-key:
    description: Public key matching private key
    required: false

runs:
  using: composite
  steps:
    - name: Build package
      id: build_deb
      uses: jiro4989/build-deb-action@v3
      with:
        package: ${{ inputs.package-name }}
        package_root: ${{ inputs.package-root }}
        maintainer: ${{ inputs.maintainer }}
        version: ${{ inputs.version }}
        arch: ${{ inputs.arch }}
        depends: ${{ inputs.depends }}
        desc: ${{ inputs.description }}
        homepage: ${{ inputs.homepage }}

    - name: Install repository tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev gnupg

    - name: Import GPG keys (if provided)
      if: inputs.gpg-private-key != '' && inputs.gpg-public-key != ''
      shell: bash
      run: |
        echo "${{ inputs.gpg-private-key }}" | gpg --import
        echo "${{ inputs.gpg-public-key }}" | gpg --import
        gpg --export --armor > DEB-GPG-KEY.asc

    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: Create APT repository
      shell: bash
      run: |
        # Set paths
        REPO_DIR="apt-repo"
        POOL_DIR="${REPO_DIR}/pool/main"
        DIST_DIR="${REPO_DIR}/dists/stable"
        METADATA_DIR="${DIST_DIR}/main/binary-${{ inputs.arch }}"

        # Create structure
        mkdir -p "${POOL_DIR}" "${METADATA_DIR}"

        # Copy old packages if they exist
        if [[ -d "gh-pages/pool" ]]; then
          echo "Copying existing packages..."
          cp -a gh-pages/pool/* "${POOL_DIR}/" || true
        fi

        # Copy new package
        echo "Adding new package..."
        cp "${{ steps.build_deb.outputs.file_name }}" "${POOL_DIR}/"

        # Create Packages file
        echo "Creating Packages metadata..."
        dpkg-scanpackages --arch "${{ inputs.arch }}" "${POOL_DIR}" > "${METADATA_DIR}/Packages"
        sed -i 's|apt-repo/||g' "${METADATA_DIR}/Packages"
        gzip -k -f "${METADATA_DIR}/Packages"

        # Create Release file
        echo "Creating Release file..."
        cat > "${DIST_DIR}/Release" <<EOF
        Origin: ${{ inputs.package-name }}
        Label: ${{ inputs.package-name }}
        Suite: stable
        Codename: stable
        Architectures: ${{ inputs.arch }}
        Components: main
        Description: ${{ inputs.description }}
        Date: $(date -Ru)
        EOF

        # Generate checksums
        for hash_cmd in md5sum sha1sum sha256sum; do
          hash_type=$(echo "$hash_cmd" | tr '[:lower:]' '[:upper:]' | sed 's/SUM//')
          echo "${hash_type}:" >> "${DIST_DIR}/Release"
          for file in $(find "${DIST_DIR}" -type f ! -name "Release*" ! -name "InRelease"); do
            sum=$($hash_cmd "$file" | awk '{print $1}')
            size=$(stat -c%s "$file")
            name=$(echo "$file" | sed "s|${DIST_DIR}/||")
            echo " $sum $size $name" >> "${DIST_DIR}/Release"
          done
        done

        # Sign Release file (if GPG keys provided)
        if [[ -n "${{ inputs.gpg-private-key }}" ]]; then
          echo "Signing Release file..."
          gpg --armor --detach-sign --output "${DIST_DIR}/Release.gpg" "${DIST_DIR}/Release"
          gpg --armor --clearsign --output "${DIST_DIR}/InRelease" "${DIST_DIR}/Release"
        fi

        # Copy GPG key if exists
        if [[ -f "DEB-GPG-KEY.asc" ]]; then
          cp DEB-GPG-KEY.asc "${REPO_DIR}/"
        fi

        # Create simple root-level Packages for simpler APT source
        cp "${METADATA_DIR}/Packages" "${REPO_DIR}/"
        cp "${METADATA_DIR}/Packages.gz" "${REPO_DIR}/"
        cp "${DIST_DIR}/Release" "${REPO_DIR}/"
        if [[ -f "${DIST_DIR}/InRelease" ]]; then
          cp "${DIST_DIR}/InRelease" "${REPO_DIR}/"
        fi

        echo "Repository structure:"
        ls -laR "${REPO_DIR}"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.token }}
        publish_dir: apt-repo/
        keep_files: false
